// <auto-generated />
using System;
using Game.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RPG_API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20261005084313_inital_create")]
    partial class inital_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ApiRequestLogs");
                });

            modelBuilder.Entity("Game.Domain.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enemies");

                    b.HasDiscriminator().HasValue("Enemy");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Game.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentEnemyHealth")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentEnemyId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrentRoomType")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWon")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEnemyId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Game.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Game.Domain.Entities.Goblin", b =>
                {
                    b.HasBaseType("Game.Domain.Entities.Enemy");

                    b.HasDiscriminator().HasValue("Goblin");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Damage = 6,
                            Health = 30,
                            MaxHealth = 30,
                            Name = "Goblin",
                            Speed = 14
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Orc", b =>
                {
                    b.HasBaseType("Game.Domain.Entities.Enemy");

                    b.HasDiscriminator().HasValue("Orc");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Damage = 14,
                            Health = 70,
                            MaxHealth = 70,
                            Name = "Orc",
                            Speed = 6
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Skeleton", b =>
                {
                    b.HasBaseType("Game.Domain.Entities.Enemy");

                    b.HasDiscriminator().HasValue("Skeleton");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 8,
                            Health = 40,
                            MaxHealth = 40,
                            Name = "Skeleton",
                            Speed = 10
                        });
                });

            modelBuilder.Entity("Game.Domain.Entities.Game", b =>
                {
                    b.HasOne("Game.Domain.Entities.Enemy", "CurrentEnemy")
                        .WithMany("Games")
                        .HasForeignKey("CurrentEnemyId");

                    b.HasOne("Game.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentEnemy");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Domain.Entities.Enemy", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
